name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: 0.7.0
    
    - name: test
      run: zig build test
